click_map/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', include("map.urls")),
]

map/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('view', views.view_map, name="view"),
    path('log', views.PointerListView.as_view(), name="log"),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

map/models.py
from django.contrib.gis.db import models

# Create your models here.

class Pointer(models.Model):
    """This is class for model of coorfinate of click on the map"""
    
    location = models.PointField()

map/views.py
from django.shortcuts import render
from .models import Pointer
from django.contrib.gis.geos import Point
import json
from django.views import generic


def view_map(request):
    """This function displays the map."""

    return render(request, "map/map.html")


class PointerListView(generic.ListView):
    """This class hanles POST and GET requests for pointers. 
    It allows to display all pointers."""
    
    model = Pointer
    paginate_by = 13
    template_name = "map/log.html"
    
    def post(self, request, *argv, **kwarg):
        """This is a handler for get queries"""

        latlng = json.loads(request.body)
        point = Point(
            float(latlng["lat"]),
            float(latlng["lng"]),
            srid=4326
        )

        pointer = Pointer(location=point)
        pointer.save()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    
    	{% block title %}<title>Map</title>{% endblock %}

    	<meta charset="utf-8" />
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    	<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>

    	<link rel="stylesheet" href="{% static 'map/css/style.css' %}">
    
    </head>
    <body >
        <div class="main">
            {% block content %} {% endblock %}

            {% block pagination %}
              {% if is_paginated %}
                  <div class="pagination">
                  
                    <div class="orange-color" style="position: absolute; top:90%; left: 45%;" >
                        <span class=" page">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span >
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                  
                  </div> 
              {% endif %}
            {% endblock %}

        </div>    
    </body>

</head>

templates/map/log.html
{% extends 'base.html' %}

{% block content %}

<a class="log" href="{% url 'view' %}">Map</a>

    {% if pointer_list %}
        
        <div class="coords">

            {% for pointer in pointer_list %}

                <div class="coord"> {{pointer.location.x}} {{pointer.location.y}} </div>

            {% endfor %}
            
        </div>

    {% endif %}

{% endblock %}

templates/map/map.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	
	<div class="title">
		click map
	</div>
	<div id="mapid"></div>
	<script type="text/javascript" src={% static "map/js/map_listener.js" %}></script>
	<a class="log" href="{% url 'log' %}">Log</a>

{% endblock %}